# Generated by Django 4.0.4 on 2022-05-27 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobs',
            old_name='company_name',
            new_name='company_name1',
        ),
    ]
