# Generated by Django 4.0.4 on 2022-05-27 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0002_rename_company_name_jobs_company_name1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobs',
            old_name='company_name1',
            new_name='company_name',
        ),
        migrations.RenameField(
            model_name='jobs',
            old_name='job_title',
            new_name='job_title_name',
        ),
    ]
